# CMake generated Testfile for 
# Source directory: /home/johatech/dev/PotreeConverter/Converter/libs/brotli
# Build directory: /home/johatech/dev/PotreeConverter/build/Converter/libs/brotli
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(roundtrip/c/enc/encode.c/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=1" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/enc/encode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/encode.c.1" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=6" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/enc/encode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/encode.c.6" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=9" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/enc/encode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/encode.c.9" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/enc/encode.c/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=11" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/enc/encode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/encode.c.11" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/enc/encode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=1" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/common/dictionary.h" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/dictionary.h.1" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=6" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/common/dictionary.h" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/dictionary.h.6" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=9" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/common/dictionary.h" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/dictionary.h.9" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/common/dictionary.h/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=11" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/common/dictionary.h" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/dictionary.h.11" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/common/dictionary.h/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/1 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=1" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/dec/decode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/decode.c.1" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/1 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/6 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=6" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/dec/decode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/decode.c.6" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/6 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/9 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=9" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/dec/decode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/decode.c.9" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/9 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
add_test(roundtrip/c/dec/decode.c/11 "/usr/bin/cmake" "-DBROTLI_WRAPPER=" "-DBROTLI_WRAPPER_LD_PREFIX=" "-DBROTLI_CLI=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/brotli" "-DQUALITY=11" "-DINPUT=/home/johatech/dev/PotreeConverter/Converter/libs/brotli/c/dec/decode.c" "-DOUTPUT=/home/johatech/dev/PotreeConverter/build/Converter/libs/brotli/decode.c.11" "-P" "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/tests/run-roundtrip-test.cmake")
set_tests_properties(roundtrip/c/dec/decode.c/11 PROPERTIES  _BACKTRACE_TRIPLES "/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;308;add_test;/home/johatech/dev/PotreeConverter/Converter/libs/brotli/CMakeLists.txt;0;")
